package pe.edu.sistemas.sisgr.domain;
// Generated 02/05/2018 07:58:08 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Activo generated by hbm2java
 */
@Entity
@Table(name = "activo", catalog = "dbbuensabor")
public class Activo implements java.io.Serializable {

	private Integer idactivo;
	private String activoTipo;
	private Float activoPrecio;
	private String activoNombre;
	private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);

	public Activo() {
	}

	public Activo(String activoTipo, Float activoPrecio, String activoNombre, Set<DetallePedido> detallePedidos,
			Set<Menu> menus) {
		this.activoTipo = activoTipo;
		this.activoPrecio = activoPrecio;
		this.activoNombre = activoNombre;
		this.detallePedidos = detallePedidos;
		this.menus = menus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDACTIVO", unique = true, nullable = false)
	public Integer getIdactivo() {
		return this.idactivo;
	}

	public void setIdactivo(Integer idactivo) {
		this.idactivo = idactivo;
	}

	@Column(name = "ACTIVO_TIPO", length = 20)
	public String getActivoTipo() {
		return this.activoTipo;
	}

	public void setActivoTipo(String activoTipo) {
		this.activoTipo = activoTipo;
	}

	@Column(name = "ACTIVO_PRECIO", precision = 10)
	public Float getActivoPrecio() {
		return this.activoPrecio;
	}

	public void setActivoPrecio(Float activoPrecio) {
		this.activoPrecio = activoPrecio;
	}

	@Column(name = "ACTIVO_NOMBRE", length = 50)
	public String getActivoNombre() {
		return this.activoNombre;
	}

	public void setActivoNombre(String activoNombre) {
		this.activoNombre = activoNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activo")
	public Set<DetallePedido> getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activo")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

}
