package pe.edu.sistemas.sisgr.domain;
// Generated 29/04/2018 04:35:34 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "dbbuensabor")
public class Cliente implements java.io.Serializable {

	private Integer idcliente;
	private Persona persona;
	private String clienteTipoCliente;
	private String clienteRuc;
	private Integer clienteDni;
	private Set<Reserva> reservas = new HashSet<Reserva>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Cliente() {
	}

	public Cliente(String clienteTipoCliente) {
		this.clienteTipoCliente = clienteTipoCliente;
	}

	public Cliente(Persona persona, String clienteTipoCliente, String clienteRuc, Integer clienteDni,
			Set<Reserva> reservas, Set<Pedido> pedidos) {
		this.persona = persona;
		this.clienteTipoCliente = clienteTipoCliente;
		this.clienteRuc = clienteRuc;
		this.clienteDni = clienteDni;
		this.reservas = reservas;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDCLIENTE", unique = true, nullable = false)
	public Integer getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(Integer idcliente) {
		this.idcliente = idcliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENTE_IDPERSONA")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "CLIENTE_TIPO_CLIENTE", nullable = false, length = 10)
	public String getClienteTipoCliente() {
		return this.clienteTipoCliente;
	}

	public void setClienteTipoCliente(String clienteTipoCliente) {
		this.clienteTipoCliente = clienteTipoCliente;
	}

	@Column(name = "CLIENTE_RUC", length = 45)
	public String getClienteRuc() {
		return this.clienteRuc;
	}

	public void setClienteRuc(String clienteRuc) {
		this.clienteRuc = clienteRuc;
	}

	@Column(name = "CLIENTE_DNI")
	public Integer getClienteDni() {
		return this.clienteDni;
	}

	public void setClienteDni(Integer clienteDni) {
		this.clienteDni = clienteDni;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
