package pe.edu.sistemas.sisgr.domain;
// Generated 29/04/2018 04:35:34 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePedido generated by hbm2java
 */
@Entity
@Table(name = "detalle_pedido", catalog = "dbbuensabor")
public class DetallePedido implements java.io.Serializable {

	private Integer iddetallePedido;
	private Activo activo;
	private Pedido pedido;
	private int detallePedidoCantidad;

	public DetallePedido() {
	}

	public DetallePedido(int detallePedidoCantidad) {
		this.detallePedidoCantidad = detallePedidoCantidad;
	}

	public DetallePedido(Activo activo, Pedido pedido, int detallePedidoCantidad) {
		this.activo = activo;
		this.pedido = pedido;
		this.detallePedidoCantidad = detallePedidoCantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDDETALLE_PEDIDO", unique = true, nullable = false)
	public Integer getIddetallePedido() {
		return this.iddetallePedido;
	}

	public void setIddetallePedido(Integer iddetallePedido) {
		this.iddetallePedido = iddetallePedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DETALLE_PEDIDO_IDACTIVO")
	public Activo getActivo() {
		return this.activo;
	}

	public void setActivo(Activo activo) {
		this.activo = activo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DETALLE_PEDIDO_IDPEDIDO")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Column(name = "DETALLE_PEDIDO_CANTIDAD", nullable = false)
	public int getDetallePedidoCantidad() {
		return this.detallePedidoCantidad;
	}

	public void setDetallePedidoCantidad(int detallePedidoCantidad) {
		this.detallePedidoCantidad = detallePedidoCantidad;
	}

}
