package pe.edu.sistemas.sisgr.domain;
// Generated 29/04/2018 04:35:34 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "dbbuensabor")
public class Menu implements java.io.Serializable {

	private Integer idmenu;
	private Activo activo;
	private Integer menuCodigo;
	private Date menuFecha;

	public Menu() {
	}

	public Menu(Activo activo) {
		this.activo = activo;
	}

	public Menu(Activo activo, Integer menuCodigo, Date menuFecha) {
		this.activo = activo;
		this.menuCodigo = menuCodigo;
		this.menuFecha = menuFecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDMENU", unique = true, nullable = false)
	public Integer getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(Integer idmenu) {
		this.idmenu = idmenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_IDACTIVO", nullable = false)
	public Activo getActivo() {
		return this.activo;
	}

	public void setActivo(Activo activo) {
		this.activo = activo;
	}

	@Column(name = "MENU_CODIGO")
	public Integer getMenuCodigo() {
		return this.menuCodigo;
	}

	public void setMenuCodigo(Integer menuCodigo) {
		this.menuCodigo = menuCodigo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MENU_FECHA", length = 10)
	public Date getMenuFecha() {
		return this.menuFecha;
	}

	public void setMenuFecha(Date menuFecha) {
		this.menuFecha = menuFecha;
	}

}
