package pe.edu.sistemas.sisgr.domain;
// Generated 29/04/2018 04:35:34 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mesa generated by hbm2java
 */
@Entity
@Table(name = "mesa", catalog = "dbbuensabor", uniqueConstraints = @UniqueConstraint(columnNames = "MESA_NUMERO"))
public class Mesa implements java.io.Serializable {

	private Integer idmesa;
	private Integer mesaMin;
	private Integer mesaMax;
	private Integer mesaNumero;
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Mesa() {
	}

	public Mesa(Integer mesaMin, Integer mesaMax, Integer mesaNumero, Set<Reserva> reservas) {
		this.mesaMin = mesaMin;
		this.mesaMax = mesaMax;
		this.mesaNumero = mesaNumero;
		this.reservas = reservas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDMESA", unique = true, nullable = false)
	public Integer getIdmesa() {
		return this.idmesa;
	}

	public void setIdmesa(Integer idmesa) {
		this.idmesa = idmesa;
	}

	@Column(name = "MESA_MIN")
	public Integer getMesaMin() {
		return this.mesaMin;
	}

	public void setMesaMin(Integer mesaMin) {
		this.mesaMin = mesaMin;
	}

	@Column(name = "MESA_MAX")
	public Integer getMesaMax() {
		return this.mesaMax;
	}

	public void setMesaMax(Integer mesaMax) {
		this.mesaMax = mesaMax;
	}

	@Column(name = "MESA_NUMERO", unique = true)
	public Integer getMesaNumero() {
		return this.mesaNumero;
	}

	public void setMesaNumero(Integer mesaNumero) {
		this.mesaNumero = mesaNumero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesa")
	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
