package pe.edu.sistemas.sisgr.domain;
// Generated 02/05/2018 07:58:08 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "dbbuensabor")
public class Pedido implements java.io.Serializable {

	private Integer idpedido;
	private Cliente cliente;
	private Trabajador trabajador;
	private char pedidoEstado;
	private Date pedidoFecha;
	private String pedidoMonto;
	private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);
	private Set<ComprobantePago> comprobantePagos = new HashSet<ComprobantePago>(0);

	public Pedido() {
	}

	public Pedido(char pedidoEstado, Date pedidoFecha) {
		this.pedidoEstado = pedidoEstado;
		this.pedidoFecha = pedidoFecha;
	}

	public Pedido(Cliente cliente, Trabajador trabajador, char pedidoEstado, Date pedidoFecha, String pedidoMonto,
			Set<DetallePedido> detallePedidos, Set<ComprobantePago> comprobantePagos) {
		this.cliente = cliente;
		this.trabajador = trabajador;
		this.pedidoEstado = pedidoEstado;
		this.pedidoFecha = pedidoFecha;
		this.pedidoMonto = pedidoMonto;
		this.detallePedidos = detallePedidos;
		this.comprobantePagos = comprobantePagos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPEDIDO", unique = true, nullable = false)
	public Integer getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(Integer idpedido) {
		this.idpedido = idpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PEDIDO_IDCLIENTE")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PEDIDO_IDTRABAJADOR")
	public Trabajador getTrabajador() {
		return this.trabajador;
	}

	public void setTrabajador(Trabajador trabajador) {
		this.trabajador = trabajador;
	}

	@Column(name = "PEDIDO_ESTADO", nullable = false, length = 1)
	public char getPedidoEstado() {
		return this.pedidoEstado;
	}

	public void setPedidoEstado(char pedidoEstado) {
		this.pedidoEstado = pedidoEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PEDIDO_FECHA", nullable = false, length = 10)
	public Date getPedidoFecha() {
		return this.pedidoFecha;
	}

	public void setPedidoFecha(Date pedidoFecha) {
		this.pedidoFecha = pedidoFecha;
	}

	@Column(name = "PEDIDO_MONTO", length = 45)
	public String getPedidoMonto() {
		return this.pedidoMonto;
	}

	public void setPedidoMonto(String pedidoMonto) {
		this.pedidoMonto = pedidoMonto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<DetallePedido> getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<ComprobantePago> getComprobantePagos() {
		return this.comprobantePagos;
	}

	public void setComprobantePagos(Set<ComprobantePago> comprobantePagos) {
		this.comprobantePagos = comprobantePagos;
	}

}
