package pe.edu.sistemas.sisgr.domain;
// Generated 02/05/2018 07:58:08 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", catalog = "dbbuensabor")
public class Persona implements java.io.Serializable {

	private Integer idpersona;
	private String personaNombre;
	private String personaApellido;
	private String personaTelefono;
	private String personaDireccion;
	private String personaEmail;
	private String personaTipo;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

	public Persona() {
	}

	public Persona(String personaNombre, String personaApellido, String personaTelefono, String personaDireccion,
			String personaEmail, String personaTipo, Set<Cliente> clientes, Set<Usuario> usuarios,
			Set<Trabajador> trabajadors) {
		this.personaNombre = personaNombre;
		this.personaApellido = personaApellido;
		this.personaTelefono = personaTelefono;
		this.personaDireccion = personaDireccion;
		this.personaEmail = personaEmail;
		this.personaTipo = personaTipo;
		this.clientes = clientes;
		this.usuarios = usuarios;
		this.trabajadors = trabajadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPERSONA", unique = true, nullable = false)
	public Integer getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(Integer idpersona) {
		this.idpersona = idpersona;
	}

	@Column(name = "PERSONA_NOMBRE", length = 45)
	public String getPersonaNombre() {
		return this.personaNombre;
	}

	public void setPersonaNombre(String personaNombre) {
		this.personaNombre = personaNombre;
	}

	@Column(name = "PERSONA_APELLIDO", length = 45)
	public String getPersonaApellido() {
		return this.personaApellido;
	}

	public void setPersonaApellido(String personaApellido) {
		this.personaApellido = personaApellido;
	}

	@Column(name = "PERSONA_TELEFONO", length = 45)
	public String getPersonaTelefono() {
		return this.personaTelefono;
	}

	public void setPersonaTelefono(String personaTelefono) {
		this.personaTelefono = personaTelefono;
	}

	@Column(name = "PERSONA_DIRECCION", length = 100)
	public String getPersonaDireccion() {
		return this.personaDireccion;
	}

	public void setPersonaDireccion(String personaDireccion) {
		this.personaDireccion = personaDireccion;
	}

	@Column(name = "PERSONA_EMAIL", length = 45)
	public String getPersonaEmail() {
		return this.personaEmail;
	}

	public void setPersonaEmail(String personaEmail) {
		this.personaEmail = personaEmail;
	}

	@Column(name = "PERSONA_TIPO", length = 45)
	public String getPersonaTipo() {
		return this.personaTipo;
	}

	public void setPersonaTipo(String personaTipo) {
		this.personaTipo = personaTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Trabajador> getTrabajadors() {
		return this.trabajadors;
	}

	public void setTrabajadors(Set<Trabajador> trabajadors) {
		this.trabajadors = trabajadors;
	}

}
