package pe.edu.sistemas.sisgr.domain;
// Generated 29/04/2018 04:35:34 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva", catalog = "dbbuensabor")
public class Reserva implements java.io.Serializable {

	private Integer idreserva;
	private Cliente cliente;
	private Mesa mesa;
	private Date reservaFecha;
	private Integer reservaCantidad;
	private String reservaTipo;
	private byte[] reservaEstado;
	private Float reservaHora;

	public Reserva() {
	}

	public Reserva(Date reservaFecha) {
		this.reservaFecha = reservaFecha;
	}

	public Reserva(Cliente cliente, Mesa mesa, Date reservaFecha, Integer reservaCantidad, String reservaTipo,
			byte[] reservaEstado, Float reservaHora) {
		this.cliente = cliente;
		this.mesa = mesa;
		this.reservaFecha = reservaFecha;
		this.reservaCantidad = reservaCantidad;
		this.reservaTipo = reservaTipo;
		this.reservaEstado = reservaEstado;
		this.reservaHora = reservaHora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDRESERVA", unique = true, nullable = false)
	public Integer getIdreserva() {
		return this.idreserva;
	}

	public void setIdreserva(Integer idreserva) {
		this.idreserva = idreserva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESERVA_IDCLIENTE")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESERVA_IDMESA")
	public Mesa getMesa() {
		return this.mesa;
	}

	public void setMesa(Mesa mesa) {
		this.mesa = mesa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RESERVA_FECHA", nullable = false, length = 10)
	public Date getReservaFecha() {
		return this.reservaFecha;
	}

	public void setReservaFecha(Date reservaFecha) {
		this.reservaFecha = reservaFecha;
	}

	@Column(name = "RESERVA_CANTIDAD")
	public Integer getReservaCantidad() {
		return this.reservaCantidad;
	}

	public void setReservaCantidad(Integer reservaCantidad) {
		this.reservaCantidad = reservaCantidad;
	}

	@Column(name = "RESERVA_TIPO", length = 25)
	public String getReservaTipo() {
		return this.reservaTipo;
	}

	public void setReservaTipo(String reservaTipo) {
		this.reservaTipo = reservaTipo;
	}

	@Column(name = "RESERVA_ESTADO")
	public byte[] getReservaEstado() {
		return this.reservaEstado;
	}

	public void setReservaEstado(byte[] reservaEstado) {
		this.reservaEstado = reservaEstado;
	}

	@Column(name = "RESERVA_HORA", precision = 10)
	public Float getReservaHora() {
		return this.reservaHora;
	}

	public void setReservaHora(Float reservaHora) {
		this.reservaHora = reservaHora;
	}

}
