package pe.edu.sistemas.sisgr.domain;
// Generated 02/05/2018 07:58:08 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trabajador generated by hbm2java
 */
@Entity
@Table(name = "trabajador", catalog = "dbbuensabor")
public class Trabajador implements java.io.Serializable {

	private Integer idtrabajador;
	private Persona persona;
	private float trabajadorSueldo;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Trabajador() {
	}

	public Trabajador(float trabajadorSueldo) {
		this.trabajadorSueldo = trabajadorSueldo;
	}

	public Trabajador(Persona persona, float trabajadorSueldo, Set<Pedido> pedidos) {
		this.persona = persona;
		this.trabajadorSueldo = trabajadorSueldo;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDTRABAJADOR", unique = true, nullable = false)
	public Integer getIdtrabajador() {
		return this.idtrabajador;
	}

	public void setIdtrabajador(Integer idtrabajador) {
		this.idtrabajador = idtrabajador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRABAJADOR_IDPERSONA")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "TRABAJADOR_SUELDO", nullable = false, precision = 10)
	public float getTrabajadorSueldo() {
		return this.trabajadorSueldo;
	}

	public void setTrabajadorSueldo(float trabajadorSueldo) {
		this.trabajadorSueldo = trabajadorSueldo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trabajador")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
